services:
  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - /home/plex/overseerr/config:/app/config
    ports:
      - "5055:5055"
