services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment:
      - "OLLAMA_BASE_URL=http://ollama:11434"
      - WEBUI_AUTH=false
    restart: unless-stopped

volumes:
  open-webui: {}

networks:
  tunnel:
    external: true
