services:
  rtsp-to-web:
    container_name: "rtsp-to-web"
    image: ghcr.io/deepch/rtsptoweb:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./config.json:/config/config.json
