services:
  speedtest-tracker:
    image: lscr.io/linuxserver/speedtest-tracker:latest
    container_name: speedtest-tracker
    restart: unless-stopped
    ports:
      - "8765:80"
    volumes:
      - speedtest-data:/config
    env_file:
      - ../../.env
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - DB_CONNECTION=sqlite
      - SPEEDTEST_SCHEDULE=*/5 * * * * # Run every 5 minutes

volumes:
  speedtest-data:
