services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    restart: unless-stopped
    container_name: flaresolverr
    volumes:
      - /home/darvin/flaresolverr/config:/config
    ports:
      - "8191:8191"
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.flaresolverr.entrypoints=http"
      - "traefik.http.routers.flaresolverr.rule=Host(`flaresolverr.darvinlabs.com`)"
      - "traefik.http.middlewares.flaresolverr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.flaresolverr.middlewares=flaresolverr-https-redirect,secured@file"
      - "traefik.http.routers.flaresolverr-secure.rule=Host(`flaresolverr.darvinlabs.com`)"
      - "traefik.http.routers.flaresolverr-secure.tls=true"
      - "traefik.http.routers.flaresolverr-secure.entrypoints=https"
      - "traefik.http.routers.flaresolverr-secure.service=flaresolverr"
      - "traefik.http.services.flaresolverr.loadbalancer.server.port=8191"
      - "traefik.tcp.routers.flaresolverr.rule=HostSNI(`flaresolverr.darvinlabs.com`)"
      - "traefik.tcp.routers.flaresolverr.tls=true"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
