services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=America/Sao_Paulo
      - WATCHTOWER_CLEANUP=true                # Remove old images after update
      - WATCHTOWER_SCHEDULE=0 0 4 * * *        # Run at 4 AM daily
      - WATCHTOWER_INCLUDE_STOPPED=false
      - WATCHTOWER_REVIVE_STOPPED=false
