services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/qbittorrent/config:/config
      - /mnt/storage/Download:/downloads
    ports:
      - "8080:8080"
      - "62609:62609"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.torrent.entrypoints=http"
      - "traefik.http.routers.torrent.rule=Host(`torrent.darvinlabs.com`)"
      - "traefik.http.middlewares.torrent-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.torrent.middlewares=torrent-https-redirect,secured@file"
      - "traefik.http.routers.torrent-secure.rule=Host(`torrent.darvinlabs.com`)"
      - "traefik.http.routers.torrent-secure.tls=true"

      - "traefik.http.routers.torrent-secure.entrypoints=https"
      - "traefik.http.routers.torrent-secure.service=torrent"
      - "traefik.http.services.torrent.loadbalancer.server.port=8080"

      - "traefik.tcp.routers.torrent.rule=HostSNI(`torrent.darvinlabs.com`)"
      - "traefik.tcp.routers.torrent.tls=true"
      - "traefik.tcp.services.torrent.loadbalancer.server.port=62609"

      - "traefik.docker.network=proxy"
networks:
  proxy:
    external: true
