services:
  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    container_name: overseerr
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - /home/plex/overseerr/config:/app/config
    ports:
      - "5055:5055"
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.entrypoints=http"
      - "traefik.http.routers.overseerr.rule=Host(`overseerr.yourdomain.com`)"
      - "traefik.http.middlewares.overseerr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.overseerr.middlewares=overseerr-https-redirect"
      - "traefik.http.routers.overseerr-secure.entrypoints=https"
      - "traefik.http.routers.overseerr-secure.rule=Host(`overseerr.yourdomain.com`)"
      - "traefik.http.routers.overseerr-secure.tls=true"
      - "traefik.http.routers.overseerr-secure.service=overseerr"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
