---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services/

- Media:
    - Plex:
        icon: plex
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:32400/web
        description: Media Server
    - Radarr:
        icon: radarr
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:7878/
        description: Movie Manager
    - Sonarr:
        icon: sonarr
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8989/
        description: TV Show Manager
    - Prowlarr:
        icon: prowlarr
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:9696/
        description: Indexer Manager
    - qBittorrent:
        icon: qbittorrent
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8080/
        description: Torrent Client

- Utilities:
    - Speedtest Tracker:
        icon: speedtest-tracker
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8765/
        description: Network Speed Monitor

    - Vaultwarden:
        icon: bitwarden
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:8222/
        description: Password Manager

- Infrastructure:
    - Portainer:
        icon: portainer
        href: https://{{HOMEPAGE_VAR_SERVER_IP}}:9443/
        description: Docker Management
    - Uptime Kuma:
        icon: uptime-kuma
        href: http://{{HOMEPAGE_VAR_SERVER_IP}}:3001/
        description: Uptime Monitor
