services:
  qbittorrent:
    image: linuxserver/qbittorrent:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - WEBUI_PORT=8080
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/qbittorrent/config:/config
      - /mnt/storage/Download:/downloads
    ports:
      - "8080:8080"
      - "62609:62609"

  jackett:
    image: ghcr.io/linuxserver/jackett:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/jackett/downloads:/downloads
      - /home/darvin/jackett/config:/config
    ports:
      - "9117:9117"

  bazarr:
    image: ghcr.io/linuxserver/bazarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/Media/Movies:/movies
      - /mnt/storage/Media/TV Show:/tv
      - /home/darvin/bazarr/appdata/config:/config
    ports:
      - "6767:6767"

  overseerr:
    image: sctx/overseerr
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PORT=5055
    volumes:
      - /home/darvin/overseerr/config:/app/config
    ports:
      - "5055:5055"

  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/prowlarr/config:/config
    ports:
      - "9696:9696"

  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/radarr/appdata/config:/config
      - /mnt/storage/Download:/downloads
      - /mnt/storage/Media/Movies:/movies
    ports:
      - "7878:7878"

  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/sonarr/appdata/config:/config
      - /mnt/storage/Media/Movies:/tv
      - /mnt/storage/Download:/downloads
    ports:
      - "8989:8989"

  plex:
    image: plexinc/pms-docker:latest
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
      - VA_DRIVER=IHD
      - PLEX_HW_TRANS_MAX=16
    volumes:
      - /home/darvin/plex/config:/config
      - /home/darvin/plex/data:/data
      - /home/darvin/plex/transcode:/transcode
      - /mnt/storage/Media/:/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/bus/usb:/dev/bus/usb
    network_mode: host
