services:
  ivredb:
    image: mongo
    container_name: ivredb
    volumes:
      - ./var_lib_mongodb:/data/db
    restart: always
  ivreuwsgi:
    image: ivre/web-uwsgi
    container_name: ivreuwsgi
    restart: always
    depends_on:
      - ivredb
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
  ivredoku:
    image: ivre/web-doku
    container_name: ivredoku
    restart: always
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
  ivreweb:
    image: ivre/web
    container_name: ivreweb
    restart: always
    ports:
      - "87:80"
    depends_on:
      - ivreuwsgi
      - ivredoku
    volumes:
      - ./dokuwiki_data:/var/www/dokuwiki/data
  ivreclient:
    image: ivre/client
    container_name: ivreclient
    volumes:
      - ./ivre-share:/ivre-share
    depends_on:
      - ivredb
    stdin_open: true
    tty: true
