services:
  prowlarr:
    image: ghcr.io/hotio/prowlarr:latest
    restart: unless-stopped
    container_name: prowlarr
    environment:
      - TZ=America/Sao_Paulo
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/darvin/prowlarr/config:/config
    ports:
      - "9696:9696"
    networks:
      proxy:
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=http"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.darvinlabs.com`)"
      - "traefik.http.middlewares.prowlarr-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.prowlarr.middlewares=prowlarr-https-redirect,secured@file"
      - "traefik.http.routers.prowlarr-secure.rule=Host(`prowlarr.darvinlabs.com`)"
      - "traefik.http.routers.prowlarr-secure.tls=true"
      - "traefik.http.routers.prowlarr-secure.entrypoints=https"
      - "traefik.http.routers.prowlarr-secure.service=prowlarr"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
      - "traefik.tcp.routers.prowlarr.rule=HostSNI(`prowlarr.darvinlabs.com`)"
      - "traefik.tcp.routers.prowlarr.tls=true"
      - "traefik.docker.network=proxy"
    deploy:
      resources:
        limits:
          cpus: "1.5"
          memory: 200M

networks:
  proxy:
    external: true
